# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41d6eab481c92781eba6fa34d73e9235f14a6b76c8ff49a6f2f5a7794859ffe0bd99b0f5d02b2d53bf64558efaa819395605dd60ab2c0b5116f8c9d71374415e

test:
  secret_key_base: 5723e1bb79ec3a4bd2f8998a03673c79f9476dc3b171f12c2d09465bc86ef31fe8e200cad15f16278ed762856323389e5b8a2936604c9ec79e6d6f71513eabca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
